### ISSUE TITLE
Logs are not being generated under Logs folder

### ISSUE THREAD

**Issue by MonoAutomation** [WasiqB/coteafs-selenium#125]
Thank you for created such good framework with core java concepts.
I started learning from your framework, and now myself getting confident to implement same framework on any application.

however I have observed on thing here, it never generated logs under Logs folder? ....I have not changed any config settings, can I know exactly will these files generates only warnings? error?..or all kinds of information under logs?

Thanks.

**Comment by WasiqB** [comment]
@MonoAutomation , for logging I am using my other framework [coteafs-config](https://github.com/WasiqB/coteafs-config). So in order to generate log files under `logs` folder, you need to add `logger-config.yml` to `src/test/resources` folder. You can check my sample config file under same folder in tests for logger config example.

Also, I am happy that my framework is beneficial for you to learn something new.

**Comment by mfaisalkhatri** [comment]
Where are we on this ticket? Is there any action that requires to be taken? Or should we close this?
